"use client";
import {useEffect,useState} from "react";
import {apiV13} from "../lib/api";
type Any=Record<string,any>;
export function CICDGraphConsole(){
 const [graphs,setGraphs]=useState<Any[]>([]),[runs,setRuns]=useState<Any[]>([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([apiV13.graphs(),apiV13.ciRuns()]).then(([g,r])=>{setGraphs(g as Any[]);setRuns(r as Any[])}).catch((e:any)=>setError(e.message))},[]);
 return <>{error&&<div className="portalError">{error}</div>}<section className="v13Pipeline"><header><div><span>CI/CD GRAPH ENGINE</span><h2>Composable gates instead of one giant opaque pipeline.</h2><p>Each node is auditable and can be a sandbox job, security review, evidence generation, release action or governance gate.</p></div><button>＋ New graph</button></header><div className="v13Dag"><div><b>Source</b><small>Git commit</small></div><i>→</i><div><b>Sandbox</b><small>tests + lint</small></div><i>→</i><div><b>Evidence</b><small>SBOM + provenance</small></div><i>→</i><div><b>Security</b><small>policy gate</small></div><i>→</i><div><b>Release</b><small>immutable SHA</small></div></div></section>
 <div className="v13Split"><section className="v8Card"><div className="v8CardHead"><div><b>Pipeline graphs</b><small>Versioned DAG definitions</small></div></div><div className="v13GraphCards">{graphs.map(x=><article key={x.id}><div><span>GRAPH #{x.id}</span><em>{x.status}</em></div><b>{x.name}</b><small>Repository #{x.repository_id} · v{x.version}</small></article>)}{!graphs.length&&<div className="v8Empty">No pipeline graph yet</div>}</div></section>
 <section className="v8Card"><div className="v8CardHead"><div><b>Recent CI runs</b><small>Commit-pinned execution</small></div></div><div className="v13CiRuns">{runs.slice(0,10).map(x=><div key={x.id}><span className={`v13Dot ${x.status}`}/><div><b>Run #{x.id}</b><code>{x.commit_sha?.slice(0,12)||"pending"}</code></div><em>{x.status}</em></div>)}{!runs.length&&<div className="v8Empty">No CI run yet</div>}</div></section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Graph node contracts</b><small>All node types have explicit control-plane semantics.</small></div></div><div className="v13NodeTypes">{[["sandbox","isolated command execution"],["security","deterministic source security review"],["evidence","SPDX + SLSA-style provenance"],["gate","boolean governance decision"],["release","immutable release creation"],["noop","orchestration boundary"]].map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</div></section></>
}
