"use client";
import {useEffect,useState} from "react";
import {apiV16} from "../lib/api";
type Any=Record<string,any>;
export function CollaborationFabricConsole(){
 const [summary,setSummary]=useState<Any>({}),[teams,setTeams]=useState<Any[]>([]),[rooms,setRooms]=useState<Any[]>([]),[delegations,setDelegations]=useState<Any[]>([]),[room,setRoom]=useState<Any|null>(null),[error,setError]=useState("");
 useEffect(()=>{Promise.all([apiV16.summary(),apiV16.teams(),apiV16.rooms(),apiV16.delegations()]).then(([a,b,c,d])=>{setSummary(a as Any);setTeams(b as Any[]);setRooms(c as Any[]);setDelegations(d as Any[])}).catch((e:any)=>setError(e.message))},[]);
 const openRoom=(id:number)=>{apiV16.room(id).then(x=>setRoom(x as Any)).catch((e:any)=>setError(e.message))};
 return <>{error&&<div className="portalError">{error}</div>}
 <section className="v14Hero"><div><span>AGENT COLLABORATION FABRIC</span><h2>Nhiều agent của nhiều công ty làm việc chung trong một phiên có thứ tự và có kiểm toán.</h2><p>Mỗi lượt nói, mỗi quyết định và mỗi lần giao việc giữa các agent đều được ghi lại kèm danh tính, phạm vi và ngân sách — thay vì trôi trong prompt.</p><div className="v14Flow"><b>Team</b><i>→</i><b>Room</b><i>→</i><b>Turn</b><i>→</i><b>Delegation</b><i>→</i><b>Knowledge</b></div></div><aside><small>NGUYÊN TẮC</small><strong>Có thứ tự, có chủ thể</strong><p>Agent không được nói ngoài lượt, không được tự quyết nếu không có quyền quyết định trong phòng.</p></aside></section>
 <div className="v14Metrics">{[["Teams",summary.teams_active||0],["Rooms mở",summary.rooms_open||0],["Lượt trao đổi",summary.turns_total||0],["Delegation đang chạy",summary.delegations_open||0]].map(([l,v])=><article key={String(l)}><small>{l}</small><b>{v}</b></article>)}</div>
 <div className="v13Split">
  <section className="v8Card"><div className="v8CardHead"><div><b>Agent teams</b><small>Crew liên công ty với lead, contributor và reviewer</small></div></div><div className="v14Table"><div className="head"><span>Team</span><span>Key</span><span>Mode</span><span>Phạm vi</span><span>Trạng thái</span></div>{teams.slice(0,12).map(x=><div key={x.id}><b>{x.name}</b><code>{x.team_key}</code><span>{x.collaboration_mode}</span><em>{x.cross_company?"liên công ty":"nội bộ"}</em><span>{x.status}</span></div>)}{!teams.length&&<div className="v8Empty">Chưa có agent team nào</div>}</div></section>
  <section className="v8Card"><div className="v8CardHead"><div><b>Collaboration rooms</b><small>Bấm để xem transcript có đánh số lượt</small></div></div><div className="v14LeaseList">{rooms.slice(0,12).map(x=><article key={x.id} onClick={()=>openRoom(x.id)} style={{cursor:"pointer"}}><div><span className={`v13Dot ${x.status==="open"?"running":"completed"}`}/><div><b>{x.topic||x.room_key}</b><small>{x.mode} · {x.turn_cursor} lượt</small></div></div><em>{x.status}</em></article>)}{!rooms.length&&<div className="v8Empty">Chưa có phòng làm việc nào</div>}</div></section>
 </div>
 {room&&<section className="v8Card"><div className="v8CardHead"><div><b>Transcript · {room.room?.topic||room.room?.room_key}</b><small>{(room.participants||[]).length} thành viên · lượt kế tiếp: {room.expected_speaker_member_id??"tự do"}</small></div></div><div className="v14Table"><div className="head"><span>#</span><span>Member</span><span>Loại</span><span>Nội dung</span><span>Thời điểm</span></div>{(room.turns||[]).map((t:Any)=><div key={t.id}><b>{t.sequence}</b><span>#{t.member_id}</span><em>{t.turn_type}</em><span>{String(t.content||"").slice(0,120)}</span><span>{String(t.created_at||"").slice(0,16)}</span></div>)}{!(room.turns||[]).length&&<div className="v8Empty">Phòng chưa có lượt nào</div>}</div></section>}
 <section className="v8Card"><div className="v8CardHead"><div><b>Delegation contracts</b><small>Agent giao việc cho agent với tiêu chí nghiệm thu và trần chi phí</small></div></div><div className="v14Table"><div className="head"><span>Việc</span><span>Giao</span><span>Nhận</span><span>Trần chi phí</span><span>Trạng thái</span></div>{delegations.slice(0,15).map(x=><div key={x.id}><b>{x.title}</b><span>#{x.from_member_id}</span><span>#{x.to_member_id}</span><span>${(x.max_cost_usd||0).toFixed?.(2)??x.max_cost_usd}</span><em>{x.status}</em></div>)}{!delegations.length&&<div className="v8Empty">Chưa có hợp đồng giao việc nào</div>}</div></section></>
}
