"use client";
import {useEffect,useState} from "react";
import {AuthGate} from "./AuthGate";
import {V8AppShell} from "./V8AppShell";
import {api,apiV8} from "../lib/api";
import {activeOrganizationId} from "../lib/auth";

type Tpl={id:number;name:string;template_type:string;publisher:string;version:string;price_monthly:number;status:string;manifest_json:string};
type Job={id:number;company_name:string;status:string;company_id?:number;result_json:string;error:string;created_at:string};
const defaultManifest={industry:"Digital Commerce",departments:[{name:"Growth",agents:[{name:"Maya",role:"Growth Lead",skills:["research","analytics"]},{name:"Leo",role:"Performance Marketer",skills:["ads","copy"]}]},{name:"Operations",agents:[{name:"Iris",role:"Operations Manager",skills:["planning","reporting"]}]}]};
export function CompanyFactoryConsole(){
 const org=activeOrganizationId(); const [templates,setTemplates]=useState<Tpl[]>([]),[jobs,setJobs]=useState<Job[]>([]),[name,setName]=useState("Nova Growth Studio"),[templateId,setTemplateId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function refresh(){try{const [t,j]=await Promise.all([api.marketplace(org),apiV8.companyFactoryJobs()]);setTemplates(t as Tpl[]);setJobs(j as Job[]);}catch(e:any){setError(e.message)}} useEffect(()=>{refresh()},[]);
 async function install(){setBusy(true);setError("");try{await apiV8.companyFactoryInstall({organization_id:org,company_name:name,template_id:templateId?Number(templateId):null,manifest:templateId?{}:defaultManifest});await refresh();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <AuthGate><V8AppShell title="Company Factory" subtitle="Deploy company templates thành organization thật với departments + AI employees"><div className="v8Two"><section className="v8Card"><div className="v8CardHead"><div><b>Create a company</b><span>Manifest → Company → Departments → AI Employees → Runtime</span></div></div>{error&&<div className="v8Error">{error}</div>}<div className="v8Form one"><label>Company name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Marketplace template<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">Built-in Growth Studio demo</option>{templates.filter(t=>t.template_type==="company").map(t=><option key={t.id} value={t.id}>{t.name} · v{t.version}</option>)}</select></label></div><div className="v8Manifest"><b>Provision plan</b><div className="v8Flow"><span>Company</span><i>→</i><span>Departments</span><i>→</i><span>Members</span><i>→</i><span>OpenClaw Agents</span><i>→</i><span>Ready</span></div><pre>{JSON.stringify(defaultManifest,null,2)}</pre></div><button className="v8Primary wide" disabled={busy||!name} onClick={install}>{busy?"Installing company…":"Install Company"}</button></section><section className="v8Card"><div className="v8CardHead"><div><b>Factory health</b><span>Latest provisioning outcomes</span></div></div><div className="v8BigMetric"><strong>{jobs.filter(j=>j.status==="ready").length}</strong><span>ready installs</span></div><div className="v8BigMetric"><strong>{jobs.filter(j=>j.status==="partial").length}</strong><span>partial installs</span></div><div className="v8BigMetric"><strong>{jobs.filter(j=>j.status==="failed").length}</strong><span>failed installs</span></div></section></div><section className="v8Card"><div className="v8CardHead"><div><b>Install history</b><span>Every install is auditable and resumable at the job level</span></div><button className="v8Ghost" onClick={refresh}>Refresh</button></div><div className="v8Table"><div className="v8Tr v8FactoryHead"><span>Company</span><span>Status</span><span>Company ID</span><span>Result</span></div>{jobs.map(j=><div className="v8Tr v8Factory" key={j.id}><span><b>{j.company_name}</b><small>Job #{j.id}</small></span><span><em className={j.status}>{j.status}</em></span><span>{j.company_id||"—"}</span><span className="mono ellipsis">{j.error||j.result_json||"—"}</span></div>)}</div></section></V8AppShell></AuthGate>
}
