"use client";
import {useEffect,useMemo,useState} from "react";

const API_BASE=process.env.NEXT_PUBLIC_API_BASE||"http://localhost:8000/api";
type Chat={id:number;conversation_id:number;agent_id:number;agent_name:string;title:string;runtime_session_key:string};
type Msg={id:number;sender_name:string;content:string;message_type:string;created_at:string};

function portalToken(){return typeof window==="undefined"?null:localStorage.getItem("clawcompany_portal_token")}
async function pfetch(path:string,init:RequestInit={}){const t=portalToken();const r=await fetch(`${API_BASE}${path}`,{...init,headers:{"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{ }),...(init.headers||{})}});if(!r.ok)throw new Error(await r.text());return r}

export function CustomerChat(){
 const [chats,setChats]=useState<Chat[]>([]),[selected,setSelected]=useState<number|undefined>(),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(""),[status,setStatus]=useState(""),[error,setError]=useState("");
 const queryAgent=useMemo(()=>typeof window!=="undefined"?Number(new URLSearchParams(location.search).get("agent")):0,[]);
 async function loadChats(){try{const r=await pfetch('/portal/chats');let j=await r.json();if(queryAgent){const found=j.find((c:Chat)=>c.agent_id===queryAgent);if(found){setSelected(found.id)}else{const c=await pfetch('/portal/chats',{method:'POST',body:JSON.stringify({agent_id:queryAgent,title:'Customer AI Chat'})});const cj=await c.json();j=[cj,...j];setSelected(cj.id)}}else if(!selected&&j.length){setSelected(j[0].id)}setChats(j)}catch(e:any){setError(e.message)}}
 async function loadMessages(id:number){try{const r=await pfetch(`/portal/chats/${id}/messages`);setMessages(await r.json())}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(!portalToken()){location.href='/portal';return}loadChats()},[]);useEffect(()=>{if(selected)loadMessages(selected)},[selected]);
 async function streamRun(chatId:number,runId:string){setStatus('AI employee is working…');const t=portalToken();const r=await fetch(`${API_BASE}/portal/chats/${chatId}/runs/${runId}/events`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok){setStatus('');throw new Error(await r.text())}const reader=r.body?.getReader();const decoder=new TextDecoder();let buf='';while(reader){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});const blocks=buf.split('\n\n');buf=blocks.pop()||'';for(const block of blocks){const ev=block.split('\n').find(x=>x.startsWith('event:'));if(ev)setStatus(ev.replace('event:','').trim().replace('run.','AI · '));}}setStatus('');await loadMessages(chatId)}
 async function send(){if(!selected||!text.trim())return;const outgoing=text;setText('');setError('');setMessages(m=>[...m,{id:Date.now(),sender_name:'You',content:outgoing,message_type:'text',created_at:new Date().toISOString()}]);try{const r=await pfetch(`/portal/chats/${selected}/messages`,{method:'POST',body:JSON.stringify({content:outgoing})});const j=await r.json();await streamRun(selected,j.run_id)}catch(e:any){setError(e.message);setStatus('')}}
 const active=chats.find(c=>c.id===selected);
 return <div className="chatShell"><aside className="chatSide"><div className="portalBrand"><div className="brandMark"/><div><b>ClawCompany</b><span>Customer Conversations</span></div></div><button className="chatBack" onClick={()=>location.href='/portal'}>← Overview</button><div className="chatSideTitle">AI conversations</div>{chats.map(c=><button key={c.id} className={`chatItem ${selected===c.id?'active':''}`} onClick={()=>setSelected(c.id)}><span className="portalAvatar">{c.agent_name?.[0]||'A'}</span><span><b>{c.agent_name}</b><small>{c.title}</small></span></button>)}</aside><main className="chatMain"><header><div><span className="portalAvatar">{active?.agent_name?.[0]||'A'}</span><div><b>{active?.agent_name||'AI Employee'}</b><small>Assigned AI Employee · OpenClaw session</small></div></div><span className="chatSession">{active?.runtime_session_key||'Session starts on first message'}</span></header><div className="chatMessages">{messages.length===0&&<div className="chatWelcome"><div className="v8NinaOrb">✦</div><h2>Start working with {active?.agent_name||'your AI employee'}</h2><p>Messages stay inside your customer tenant and are routed to the assigned OpenClaw agent.</p></div>}{messages.map(m=><div key={m.id} className={`chatBubble ${m.sender_name==='AI Employee'?'ai':'user'}`}><small>{m.sender_name||'User'}</small><p>{m.content}</p></div>)}{status&&<div className="chatWorking"><i/> {status}</div>}</div><footer><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask your AI employee…"/><button onClick={send}>Send ↑</button>{error&&<span className="portalError">{error}</span>}</footer></main></div>
}
