"use client";
import {useEffect,useState} from "react";
import {apiV14} from "../lib/api";
type Any=Record<string,any>;
export function DistributedRunnersConsole(){
 const [pools,setPools]=useState<Any[]>([]),[nodes,setNodes]=useState<Any[]>([]),[leases,setLeases]=useState<Any[]>([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([apiV14.runnerPools(),apiV14.runnerNodes(),apiV14.runnerLeases()]).then(([a,b,c])=>{setPools(a as Any[]);setNodes(b as Any[]);setLeases(c as Any[])}).catch((e:any)=>setError(e.message))},[]);
 const online=nodes.filter(x=>x.status==="online").length, active=leases.filter(x=>x.status==="active").length;
 return <>{error&&<div className="portalError">{error}</div>}<section className="v14Hero"><div><span>DISTRIBUTED SECURE EXECUTION</span><h2>Lease compute to AI employees without handing them infrastructure credentials.</h2><p>The broker matches capabilities and capacity, issues short-lived lease-bound workload identity, then lets a remote runner pull only the jobs assigned to that node.</p><div className="v14Flow"><b>Agent</b><i>→</i><b>Runner Lease</b><i>→</i><b>Workload JWT</b><i>→</i><b>Remote Runner</b><i>→</i><b>Artifact / Result</b></div></div><aside><small>PRODUCTION POSTURE</small><strong>Fail closed</strong><p>Expired lease revokes workload identity. Kubernetes / Firecracker execution stays adapter-bound and cannot silently fall back to privileged local execution.</p></aside></section>
 <div className="v14Metrics">{[["Runner pools",pools.length],["Online nodes",online],["Active leases",active],["Available capacity",nodes.reduce((n,x)=>n+Math.max(0,(x.capacity||0)-(x.active_leases||0)),0)]].map(([l,v])=><article key={String(l)}><small>{l}</small><b>{v}</b></article>)}</div>
 <div className="v13Split"><section className="v8Card"><div className="v8CardHead"><div><b>Runner fleet</b><small>Heartbeat + capacity + capabilities</small></div></div><div className="v14Table"><div className="head"><span>Node</span><span>Provider</span><span>Capacity</span><span>Capabilities</span><span>Status</span></div>{nodes.map(x=><div key={x.id}><b>{x.node_key}</b><span>{x.provider}</span><span>{x.active_leases}/{x.capacity}</span><code>{(JSON.parse(x.capabilities_json||"[]") as string[]).join(", ")||"—"}</code><em>{x.status}</em></div>)}{!nodes.length&&<div className="v8Empty">No remote runner registered yet</div>}</div></section>
 <section className="v8Card"><div className="v8CardHead"><div><b>Active leases</b><small>Identity and workload are bounded to lease lifetime</small></div></div><div className="v14LeaseList">{leases.slice(0,12).map(x=><article key={x.id}><div><span className={`v13Dot ${x.status==="active"?"running":"completed"}`}/><div><b>Lease #{x.id}</b><small>{x.workload_type} · {x.workload_ref||"unbound"}</small></div></div><em>{x.status}</em></article>)}{!leases.length&&<div className="v8Empty">No lease activity</div>}</div></section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Execution provider contract</b><small>Control-plane support vs runtime availability</small></div></div><div className="v14ProviderGrid">{[["Remote pull runner","implemented","API-key node auth + lease-bound workload JWT"],["Kubernetes","adapter","Traffic + execution contracts; cluster credentials external"],["Firecracker / microVM","adapter","Broker contract only; privileged runner is separate infrastructure"],["Local","development","Never used as hidden fallback for production providers"]].map(([a,b,c])=><article key={a}><span>{b}</span><b>{a}</b><p>{c}</p></article>)}</div></section></>
}
