"use client";
import {useEffect,useMemo,useState} from "react";
import {AuthGate} from "./AuthGate";
import {V9AppShell} from "./V9AppShell";
import {api,apiV9} from "../lib/api";
import {activeOrganizationId} from "../lib/auth";

export function GoalsConsole(){
 const org=activeOrganizationId(); const [goals,setGoals]=useState<any[]>([]),[companies,setCompanies]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[cycles,setCycles]=useState<any[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [title,setTitle]=useState("Scale Nova Fashion TikTok acquisition"),[objective,setObjective]=useState("Grow qualified TikTok demand while keeping brand quality, execution risk and AI cost within policy limits."),[companyId,setCompanyId]=useState(""),[risk,setRisk]=useState("low"),[budget,setBudget]=useState("25");
 async function load(){try{const [g,c,cy]=await Promise.all([apiV9.goals(),api.companies(org),apiV9.cycles()]);setGoals(g as any[]);setCompanies(c as any[]);setCycles(cy as any[])}catch(e:any){setError(e.message)}} useEffect(()=>{load()},[]);
 async function create(){setBusy(true);setError("");try{const g=await apiV9.createGoal({organization_id:org,company_id:companyId?Number(companyId):null,title,objective,expected_outcome:"Measurable outcome with an executive report",priority:"high",risk,autonomy_mode:"inherit",deadline:"",budget_limit:budget?Number(budget):null,currency:"USD"});setSelected(g);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function plan(g:any){setBusy(true);try{const r:any=await apiV9.planGoal(g.id,{max_steps:5,project_id:null,auto_create_tasks:true});setSelected(r.goal);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function run(g:any){setBusy(true);try{const r:any=await apiV9.runGoal(g.id,{estimated_cost_per_assignment:0.25,execute_unassigned:false});await load();alert(`Cycle #${r.cycle.id}: ${r.cycle.status}`)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function tick(c:any){setBusy(true);try{await apiV9.tickCycle(c.id,true);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const selectedCycles=useMemo(()=>cycles.filter(c=>!selected||c.goal_id===selected.id),[cycles,selected]);
 return <AuthGate><V9AppShell title="Executive Goals" subtitle="Founder objective → Nina plan → governed autonomous operating cycle" action={<button className="v8Primary" disabled={busy||!title.trim()||!objective.trim()} onClick={create}>{busy?"Working…":"Create goal"}</button>}>
  {error&&<div className="v8Error">{error}</div>}
  <div className="v9Grid2"><section className="v8Card"><div className="v8CardHead"><div><b>New executive goal</b><span>Define the outcome. The OS handles decomposition and delegation.</span></div></div><div className="v9Form"><label>Goal title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Objective<textarea value={objective} onChange={e=>setObjective(e.target.value)}/></label><div className="v9FormRow"><label>Company<select value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="">Choose company for task execution</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Risk<select value={risk} onChange={e=>setRisk(e.target.value)}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label>Budget USD<input type="number" value={budget} onChange={e=>setBudget(e.target.value)}/></label></div></div></section>
   <section className="v8Card"><div className="v8CardHead"><div><b>Governance contract</b><span>Execution only advances through explicit gates</span></div></div><div className="v8Checklist"><p>✓ company-scoped delegation</p><p>✓ manager hierarchy preserved</p><p>✓ risk threshold → approval</p><p>✓ per-action + goal budget checks</p><p>✓ runtime event persistence</p><p>✓ retry / incident handling</p></div></section></div>
  <section className="v8Card"><div className="v8CardHead"><div><b>Goals</b><span>{goals.length} objectives in this organization</span></div></div><div className="v9GoalTable"><div className="v9GoalHead"><span>Goal</span><span>Status</span><span>Progress</span><span>Risk</span><span>Actions</span></div>{goals.map(g=><div className={`v9GoalLine ${selected?.id===g.id?"selected":""}`} key={g.id} onClick={()=>setSelected(g)}><span><b>{g.title}</b><small>{g.objective}</small></span><span><em className="v9Status">{g.status}</em></span><span>{g.progress||0}%</span><span>{g.risk}</span><span className="v9Actions"><button onClick={e=>{e.stopPropagation();plan(g)}} disabled={busy}>Plan</button><button onClick={e=>{e.stopPropagation();run(g)}} disabled={busy||!g.execution_plan_id}>Run</button></span></div>)}</div></section>
  <section className="v8Card"><div className="v8CardHead"><div><b>Operating cycles</b><span>{selected?`Execution history for ${selected.title}`:"Recent autonomous loops"}</span></div></div><div className="v9List">{selectedCycles.map(c=><div className="v9Cycle" key={c.id}><div><b>Cycle #{c.id}</b><small>Goal #{c.goal_id} · mode {c.mode}</small></div><em className="v9Status">{c.status}</em><button onClick={()=>tick(c)} disabled={busy||["completed","cancelled"].includes(c.status)}>Tick / reconcile</button></div>)}</div></section>
 </V9AppShell></AuthGate>
}
