"use client";
import {useEffect,useState} from "react";
import {AuthGate} from "./AuthGate";
import {V8AppShell} from "./V8AppShell";
import {api,apiV8} from "../lib/api";
import {activeOrganizationId} from "../lib/auth";

type Company={id:number;name:string}; type Project={id:number;company_id:number;name:string}; type Plan={id:number;objective:string;status:string;summary:string;created_at:string};
type PlanDetail={plan:Plan;steps:{id:number;step_index:number;title:string;description:string;owner_member_id:number|null;task_id:number|null;status:string}[]};
export function NinaPlannerConsole(){const org=activeOrganizationId();const [objective,setObjective]=useState("Launch a profitable TikTok campaign for the summer collection within 14 days"),[companyId,setCompanyId]=useState(""),[projectId,setProjectId]=useState(""),[companies,setCompanies]=useState<Company[]>([]),[projects,setProjects]=useState<Project[]>([]),[plans,setPlans]=useState<Plan[]>([]),[detail,setDetail]=useState<PlanDetail|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){try{const [c,p,pl]=await Promise.all([api.companies(org),api.projects(),apiV8.ninaPlans()]);setCompanies(c as Company[]);setProjects(p as Project[]);setPlans(pl as Plan[])}catch(e:any){setError(e.message)}} useEffect(()=>{load()},[]);
 async function create(){setBusy(true);setError("");try{const j=await apiV8.createNinaPlan({organization_id:org,objective,company_id:companyId?Number(companyId):null,project_id:projectId?Number(projectId):null,auto_create_tasks:true,max_steps:5}) as PlanDetail;setDetail(j);await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function delegate(){if(!detail)return;setBusy(true);try{await apiV8.delegateNinaPlan(detail.plan.id);setDetail({...detail,plan:{...detail.plan,status:"delegated"}});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <AuthGate><V8AppShell title="Nina Planner" subtitle="Founder objective → plan → owners → tasks → agent delegation" action={<button className="v8Primary" disabled={busy||!objective.trim()} onClick={create}>{busy?"Planning…":"Create execution plan"}</button>}><div className="v8NinaHero"><div><span className="v8Pill">AI CHIEF OF STAFF</span><h2>Give Nina the outcome, not the task list.</h2><p>Nina converts a founder-level objective into an auditable execution plan and assigns work to the current AI workforce.</p></div><div className="v8NinaOrb">N</div></div>{error&&<div className="v8Error">{error}</div>}<div className="v8Two"><section className="v8Card"><div className="v8CardHead"><div><b>Objective</b><span>What should the company achieve?</span></div></div><textarea className="v8Textarea" value={objective} onChange={e=>setObjective(e.target.value)}/><div className="v8Form"><label>Company<select value={companyId} onChange={e=>{setCompanyId(e.target.value);setProjectId("")}}><option value="">No company constraint</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Existing project<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Create a Nina project</option>{projects.filter(p=>!companyId||String(p.company_id)===companyId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div></section><section className="v8Card"><div className="v8CardHead"><div><b>Planner contract</b><span>Deterministic orchestration baseline</span></div></div><div className="v8Checklist"><p>✓ discover available AI employees</p><p>✓ create project when needed</p><p>✓ decompose into ordered steps</p><p>✓ match role → owner</p><p>✓ create Company Tasks</p><p>✓ dispatch only through Runtime Adapter</p></div></section></div>{detail&&<section className="v8Card"><div className="v8CardHead"><div><b>{detail.plan.objective}</b><span>Plan #{detail.plan.id} · {detail.plan.status}</span></div><button className="v8Primary" onClick={delegate} disabled={busy}>Delegate to AI workforce</button></div><div className="v8Timeline">{detail.steps.map((s,i)=><div className="v8TimelineRow" key={s.id}><div className="v8StepNo">{i+1}</div><div><b>{s.title}</b><p>{s.description}</p><span>Owner member #{s.owner_member_id||"unassigned"} · Task #{s.task_id||"—"}</span></div><em>{s.status}</em></div>)}</div></section>}<section className="v8Card"><div className="v8CardHead"><div><b>Recent Nina plans</b><span>Founder-level execution history</span></div></div><div className="v8PlanGrid">{plans.map(p=><button key={p.id} onClick={async()=>{try{const r=await fetch(`${process.env.NEXT_PUBLIC_API_BASE||"http://localhost:8000/api"}/nina/plans/${p.id}`,{headers:{Authorization:`Bearer ${localStorage.getItem("clawcompany_token")}`}});if(r.ok)setDetail(await r.json())}catch{}}}><span>#{p.id}</span><b>{p.objective}</b><em>{p.status}</em></button>)}</div></section></V8AppShell></AuthGate>}
