"use client";
import {useEffect,useState} from "react";
import {apiV12} from "../lib/api";
type Any=Record<string,any>;
export function ReleasesConsole(){
 const [releases,setReleases]=useState<Any[]>([]),[envs,setEnvs]=useState<Any[]>([]),[deployments,setDeployments]=useState<Any[]>([]),[err,setErr]=useState("");
 const [repo,setRepo]=useState("1"),[version,setVersion]=useState("1.0.0"),[sha,setSha]=useState(""),[env,setEnv]=useState("");
 const load=async()=>{try{const [r,e,d]=await Promise.all([apiV12.releases(),apiV12.environments(),apiV12.deployments()]);setReleases(r as Any[]);setEnvs(e as Any[]);setDeployments(d as Any[]);if(!env&&(e as Any[])[0])setEnv(String((e as Any[])[0].id));setErr("")}catch(e:any){setErr(e.message)}};useEffect(()=>{load()},[]);
 const create=async()=>{try{await apiV12.createRelease({repository_id:Number(repo),version,commit_sha:sha,release_notes:"Created from v12 release console",manifest:{source:"ui"}});await load()}catch(e:any){setErr(e.message)}};
 const deploy=async(id:number)=>{try{await apiV12.deployRelease(id,Number(env));await load()}catch(e:any){setErr(e.message)}};
 return <><div className="v12Two"><section className="v8Card"><div className="v8CardHead"><div><b>Create immutable release</b><small>Release must resolve to a Git commit SHA.</small></div></div><div className="v9Form"><label>Repository ID<input value={repo} onChange={e=>setRepo(e.target.value)}/></label><label>Version<input value={version} onChange={e=>setVersion(e.target.value)}/></label><label>Commit SHA<input value={sha} onChange={e=>setSha(e.target.value)} placeholder="full commit SHA"/></label><button className="v8Primary" onClick={create}>Create release</button></div>{err&&<div className="portalError">{err}</div>}</section><section className="v8Card"><div className="v8CardHead"><div><b>Deployment target</b><small>Production may require an approval before deploy.</small></div></div><div className="v12EnvList">{envs.map(x=><label key={x.id} className={String(x.id)===env?"active":""}><input type="radio" name="env" checked={String(x.id)===env} onChange={()=>setEnv(String(x.id))}/><div><b>{x.name}</b><small>{x.environment_type} · {x.provider}</small></div><span>{x.require_approval?"approval":"direct"}</span></label>)}</div></section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Release train</b><small>Every deployment is commit-pinned and linked to its predecessor for rollback.</small></div></div><div className="v12ReleaseGrid">{releases.map(x=><article key={x.id}><header><b>{x.version}</b><span>{x.status}</span></header><code>{x.commit_sha}</code><p>{x.release_notes||"No release notes"}</p><footer><small>repo #{x.repository_id}</small><button onClick={()=>deploy(x.id)}>Deploy →</button></footer></article>)}</div></section>
 <section className="v8Card"><div className="v8CardHead"><div><b>Recent deployments</b><small>Release lineage</small></div></div><div className="v12DeployStrip">{deployments.map(x=><article key={x.id}><span>#{x.id}</span><b>Release {x.release_id}</b><small>env #{x.environment_id} · previous #{x.previous_deployment_id||"—"}</small><em>{x.status}</em></article>)}</div></section></>
}
