"use client";
import {useEffect,useState} from "react";
import {apiV13} from "../lib/api";
type Any=Record<string,any>;
export function ReleaseManagerV13Console(){
 const [decisions,setDecisions]=useState<Any[]>([]),[strategies,setStrategies]=useState<Any[]>([]),[health,setHealth]=useState<Any[]>([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([apiV13.releaseManagerRuns(),apiV13.deploymentStrategies(),apiV13.healthRuns()]).then(([d,s,h])=>{setDecisions(d as Any[]);setStrategies(s as Any[]);setHealth(h as Any[])}).catch((e:any)=>setError(e.message))},[]);
 return <>{error&&<div className="portalError">{error}</div>}<section className="v13ReleaseHero"><div><span>RELEASE MANAGER AGENT</span><h2>Promote only when CI, security, approval and deployment health agree.</h2><p>The Release Manager is a deterministic governance service today; it can later be wrapped by an AI Release Manager without allowing the model to bypass policy.</p></div><aside><div><span>Rolling</span><b>deploy → verify → rollback</b></div><div><span>Blue/Green</span><b>verify candidate → atomic cutover</b></div><div><span>Canary</span><b>router adapter required</b></div></aside></section>
 <div className="v13Split"><section className="v8Card"><div className="v8CardHead"><div><b>Release decisions</b><small>Evidence-backed approve / hold / reject</small></div></div><div className="v13DecisionList">{decisions.map(x=><article key={x.id}><span className={`v13Decision ${x.decision}`}>{x.decision}</span><div><b>Release #{x.release_id}</b><small>{x.reason}</small></div><em>#{x.id}</em></article>)}{!decisions.length&&<div className="v8Empty">No release manager decision yet</div>}</div></section>
 <section className="v8Card"><div className="v8CardHead"><div><b>Progressive delivery</b><small>Strategy state machine</small></div></div><div className="v13StrategyList">{strategies.map(x=><article key={x.id}><div><b>{x.strategy}</b><em>{x.status}</em></div><small>release #{x.release_id} → env #{x.environment_id}</small><footer><span>{x.traffic_percent}% traffic request</span><span>{x.rollback_id?`rollback #${x.rollback_id}`:"no rollback"}</span></footer></article>)}{!strategies.length&&<div className="v8Empty">No deployment strategy run yet</div>}</div></section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Health checks</b><small>Post-deploy verification with automatic rollback hooks</small></div></div><div className="v13Health">{health.slice(0,12).map(x=><div key={x.id}><span>#{x.id}</span><b>Deployment #{x.deployment_id}</b><small>{x.successes} success · {x.failures} failure</small><em>{x.status}</em></div>)}</div></section></>
}
