"use client";
import {useEffect,useState} from "react";
import {apiV11} from "../lib/api";
type Any=Record<string,any>;
const stage=(s:string)=>({queued:0,preparing:1,prepared:2,tests_passed:3,reviewing:4,merged:5}[s]??0);
export function RepositoryDeliveryConsole(){
 const [repos,setRepos]=useState<Any[]>([]),[runs,setRuns]=useState<Any[]>([]),[selected,setSelected]=useState<Any|null>(null),[error,setError]=useState("");
 const [repo,setRepo]=useState(""),[bundle,setBundle]=useState("feature-demo"),[pipeline,setPipeline]=useState("");
 const load=async()=>{try{const [r,d]=await Promise.all([apiV11.repositories(),apiV11.deliveries()]);setRepos(r as Any[]);setRuns(d as Any[]);if(!repo&&(r as Any[])[0])setRepo(String((r as Any[])[0].id));setError("")}catch(e:any){setError(e.message)}};useEffect(()=>{load()},[]);
 const open=async(id:number)=>{try{setSelected(await apiV11.delivery(id) as Any)}catch(e:any){setError(e.message)}};
 const create=async()=>{try{const x=await apiV11.createDelivery({repository_id:Number(repo),pipeline_id:pipeline?Number(pipeline):null,artifact_bundle_key:bundle,initiated_by_member_id:null}) as Any;await load();await open(x.id)}catch(e:any){setError(e.message)}};
 const act=async(kind:string,id:number)=>{try{if(kind==="prepare")await apiV11.prepareDelivery(id);if(kind==="tests")await apiV11.testDelivery(id);if(kind==="mr")await apiV11.openMergeRequest(id);if(kind==="merge")await apiV11.mergeDelivery(id);await load();await open(id)}catch(e:any){setError(e.message)}};
 return <><div className="v11DeliveryHero"><div><span>REPOSITORY DELIVERY PIPELINE</span><h2>Agent output → tested commit → reviewed merge</h2><p>Commit Agent receives immutable artifact versions, writes them into an isolated Git worktree, generates a patch artifact, runs the configured test profile and only merges after policy gates pass.</p></div><div className="v11HeroSteps"><b>01</b><span>Prepare</span><b>02</b><span>Test</span><b>03</b><span>Review</span><b>04</b><span>Merge</span></div></div>
 <div className="v10Grid"><section className="v8Card"><div className="v8CardHead"><div><b>Start delivery</b><small>Use an Artifact Registry bundle key produced by any agent.</small></div></div><div className="v9Form"><label>Repository<select value={repo} onChange={e=>setRepo(e.target.value)}>{repos.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Artifact bundle<input value={bundle} onChange={e=>setBundle(e.target.value)}/></label><label>Pipeline ID (optional)<input value={pipeline} onChange={e=>setPipeline(e.target.value)}/></label><button className="v8Primary" onClick={create}>Create delivery run</button></div>{error&&<div className="portalError">{error}</div>}</section>
 <section className="v8Card"><div className="v8CardHead"><div><b>Selected delivery</b><small>Merge gate is computed from actual test and review state.</small></div></div>{selected?<><div className="v11Gate"><div><span>Run</span><b>#{selected.delivery.id}</b></div><div><span>Branch</span><b>{selected.delivery.source_branch||"pending"}</b></div><div><span>Tests</span><b>{selected.gate.latest_test_status||"pending"}</b></div><div><span>Approvals</span><b>{selected.gate.approvals}/{selected.gate.required_approvals}</b></div></div><div className="v11GateLine"><i className={selected.gate.allowed?"ok":""}/><span>{selected.gate.allowed?"Merge gate open":"Waiting for required checks"}</span></div><code className="v11Sha">{selected.delivery.head_commit_sha||"Commit not created yet"}</code></>:<div className="v8Empty">Select a delivery run</div>}</section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Delivery runs</b><small>Each branch is isolated per run. Artifact-to-commit provenance remains queryable.</small></div></div><div className="v11RunList">{runs.map(x=><article key={x.id} onClick={()=>open(x.id)}><div className="v11RunTop"><b>#{x.id} · {x.artifact_bundle_key}</b><span className={`v11Status ${x.status}`}>{x.status}</span></div><div className="v11Progress">{[0,1,2,3,4,5].map(i=><i key={i} className={i<=stage(x.status)?"done":""}/>)}</div><small>{x.source_branch||"branch pending"} → {x.target_branch}</small><footer><button onClick={e=>{e.stopPropagation();act("prepare",x.id)}}>Prepare</button><button onClick={e=>{e.stopPropagation();act("tests",x.id)}}>Tests</button><button onClick={e=>{e.stopPropagation();act("mr",x.id)}}>Open MR</button><button onClick={e=>{e.stopPropagation();act("merge",x.id)}}>Merge</button></footer></article>)}</div></section></>
}
