"use client";
import {useEffect,useState} from "react";
import {apiV12} from "../lib/api";
type Any=Record<string,any>;
export function SandboxesConsole(){
 const [profiles,setProfiles]=useState<Any[]>([]),[runs,setRuns]=useState<Any[]>([]),[workspaces,setWorkspaces]=useState<Any[]>([]),[err,setErr]=useState("");
 const [ws,setWs]=useState(""),[profile,setProfile]=useState(""),[cmd,setCmd]=useState("python -V");
 const load=async()=>{try{const [p,r,w]=await Promise.all([apiV12.sandboxProfiles(),apiV12.sandboxRuns(),apiV12.workspaces()]);setProfiles(p as Any[]);setRuns(r as Any[]);setWorkspaces(w as Any[]);if(!ws&&(w as Any[])[0])setWs(String((w as Any[])[0].id));if(!profile&&(p as Any[])[0])setProfile(String(((p as Any[])[0].profile||p[0]).id));setErr("")}catch(e:any){setErr(e.message)}};useEffect(()=>{load()},[]);
 const run=async()=>{try{await apiV12.runSandbox({workspace_id:Number(ws),profile_id:Number(profile),purpose:"test",command:cmd.trim().split(/\s+/),secret_grant_ids:[]});await load()}catch(e:any){setErr(e.message)}};
 return <><div className="v12Two"><section className="v8Card"><div className="v8CardHead"><div><b>Launch sandbox</b><small>argv-based execution; no shell interpolation</small></div></div><div className="v9Form"><label>Workspace<select value={ws} onChange={e=>setWs(e.target.value)}>{workspaces.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Profile<select value={profile} onChange={e=>setProfile(e.target.value)}>{profiles.map((x:any)=>{const p=x.profile||x;return <option key={p.id} value={p.id}>{p.name} · {p.provider}</option>})}</select></label><label>Command<input value={cmd} onChange={e=>setCmd(e.target.value)}/></label><button className="v8Primary" onClick={run}>Run in sandbox</button></div>{err&&<div className="portalError">{err}</div>}</section><section className="v8Card"><div className="v8CardHead"><div><b>Security profile</b><small>Docker adapter fails closed when egress policy is unavailable.</small></div></div><div className="v12Security">{profiles.slice(0,4).map((x:any)=>{const p=x.profile||x,pol=x.policy||{};return <article key={p.id}><div><b>{p.name}</b><span>{p.provider}</span></div><small>{p.image}</small><ul><li>Network: {p.network_mode}</li><li>Root FS: {p.read_only_root?"read-only":"writable"}</li><li>Memory: {p.memory_mb} MB</li><li>CPU: {p.cpu_limit}</li></ul><em>{pol.secure_default?"secure default":"review policy"}</em></article>})}</div></section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Sandbox run history</b><small>Output is bounded and secrets are mounted as temporary files.</small></div></div><div className="v12RunTable"><div className="head"><span>Run</span><span>Purpose</span><span>Workspace</span><span>Provider ref</span><span>Exit</span><span>Status</span></div>{runs.map(x=><div key={x.id}><b>#{x.id}</b><span>{x.purpose}</span><span>#{x.workspace_id}</span><code>{x.provider_run_id||"—"}</code><span>{x.exit_code??"—"}</span><em className={x.status}>{x.status}</em></div>)}</div></section></>
}
