"use client";
import {useEffect,useMemo,useState} from "react";
import {AuthGate} from "./AuthGate";
import {V8AppShell} from "./V8AppShell";
import {api,apiV8} from "../lib/api";
import {activeOrganizationId} from "../lib/auth";

type Row={id:number;member_id:number;runtime_agent_id:string;lifecycle:string;model:string;success_rate:number;cost_30d:number;risk:string};
type Member={id:number;name:string;role:string;company_id:number|null;department_id:number|null};
type Company={id:number;name:string};
type Department={id:number;company_id:number;name:string};
type Job={id:number;name:string;role:string;runtime_agent_id:string;status:string;agent_id?:number;error:string};
export function WorkforceConsole(){
 const org=activeOrganizationId(); const [rows,setRows]=useState<Row[]>([]),[members,setMembers]=useState<Member[]>([]),[companies,setCompanies]=useState<Company[]>([]),[departments,setDepartments]=useState<Department[]>([]),[jobs,setJobs]=useState<Job[]>([]),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [form,setForm]=useState({name:"Ava",role:"Growth Analyst",company_id:"",department_id:"",model:"",runtime_agent_id:""});
 async function refresh(){try{const [a,m,c,d,j]=await Promise.all([api.agents(),api.members(),api.companies(org),api.departments(),apiV8.provisioningJobs()]);setRows(a as Row[]);setMembers(m as Member[]);setCompanies(c as Company[]);setDepartments(d as Department[]);setJobs(j as Job[]);}catch(e:any){setError(e.message)}}
 useEffect(()=>{refresh()},[]);
 const memberMap=useMemo(()=>Object.fromEntries(members.map(x=>[x.id,x])),[members]);
 const filteredDeps=form.company_id?departments.filter(d=>String(d.company_id)===form.company_id):departments;
 async function hire(){setBusy(true);setError("");try{await apiV8.hireAgent({organization_id:org,name:form.name,role:form.role,company_id:form.company_id?Number(form.company_id):null,department_id:form.department_id?Number(form.department_id):null,model:form.model,runtime_agent_id:form.runtime_agent_id,manifest:{skills:["company.context","company.tasks.list"],policy:{mode:"scoped"}}});setShow(false);await refresh();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <AuthGate><V8AppShell title="AI Workforce" subtitle="Registry, employment lifecycle và OpenClaw provisioning" action={<button className="v8Primary" onClick={()=>setShow(true)}>+ Hire AI Employee</button>}>
   <div className="v8Stats"><div><small>AI employees</small><strong>{rows.length}</strong><span>active registry</span></div><div><small>Running / active</small><strong>{rows.filter(x=>x.lifecycle==="active").length}</strong><span>runtime-ready</span></div><div><small>Provisioning jobs</small><strong>{jobs.length}</strong><span>{jobs.filter(x=>x.status==="failed").length} failed</span></div><div><small>30d internal cost</small><strong>${rows.reduce((a,b)=>a+(b.cost_30d||0),0).toFixed(1)}</strong><span>tracked</span></div></div>
   {error&&<div className="v8Error">{error}</div>}
   <section className="v8Card"><div className="v8CardHead"><div><b>AI Employee Registry</b><span>Member ↔ Agent ↔ OpenClaw runtime binding</span></div><button className="v8Ghost" onClick={refresh}>Refresh</button></div><div className="v8Table"><div className="v8Tr v8Th"><span>Employee</span><span>Role</span><span>Runtime ID</span><span>Model</span><span>Status</span><span>Risk</span></div>{rows.map(a=>{const m=memberMap[a.member_id];return <div className="v8Tr" key={a.id}><span><b>{m?.name||`Agent #${a.id}`}</b><small>ID {a.id}</small></span><span>{m?.role||"—"}</span><span className="mono">{a.runtime_agent_id}</span><span>{a.model||"default"}</span><span><i className={`v8Dot ${a.lifecycle}`}/>{a.lifecycle}</span><span className={`v8Risk ${a.risk}`}>{a.risk}</span></div>})}</div></section>
   <section className="v8Card"><div className="v8CardHead"><div><b>Provisioning history</b><span>Company OS → runtime creation → ready/failed</span></div></div><div className="v8JobGrid">{jobs.slice(0,8).map(j=><div className="v8Job" key={j.id}><div><b>{j.name}</b><span>{j.role}</span></div><code>{j.runtime_agent_id}</code><em className={j.status}>{j.status}</em>{j.error&&<small>{j.error}</small>}</div>)}</div></section>
   {show&&<div className="v8Modal"><div className="v8ModalCard"><div className="v8CardHead"><div><b>Hire AI Employee</b><span>Tạo employment record và provision sang OpenClaw runtime</span></div><button className="v8Icon" onClick={()=>setShow(false)}>×</button></div><div className="v8Form"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Role<input value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/></label><label>Company<select value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value,department_id:""})}><option value="">Organization-level</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Department<select value={form.department_id} onChange={e=>setForm({...form,department_id:e.target.value})}><option value="">None</option>{filteredDeps.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Model<input placeholder="Runtime default" value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Runtime Agent ID<input placeholder="Auto-generate" value={form.runtime_agent_id} onChange={e=>setForm({...form,runtime_agent_id:e.target.value})}/></label></div><div className="v8ModalActions"><button className="v8Ghost" onClick={()=>setShow(false)}>Cancel</button><button className="v8Primary" disabled={busy||!form.name||!form.role} onClick={hire}>{busy?"Provisioning…":"Hire & Provision"}</button></div></div></div>}
 </V8AppShell></AuthGate>
}
