"use client";
import {useEffect,useState} from "react";
import {apiV13} from "../lib/api";
type Any=Record<string,any>;
export function WorkspaceGatewayV13Console(){
 const [sessions,setSessions]=useState<Any[]>([]),[providers,setProviders]=useState<Any[]>([]),[ops,setOps]=useState<Any[]>([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([apiV13.gatewaySessions(),apiV13.executionProviders(),apiV13.gatewayOperations()]).then(([a,b,c])=>{setSessions(a as Any[]);setProviders(b as Any[]);setOps(c as Any[])}).catch((e:any)=>setError(e.message))},[]);
 return <>{error&&<div className="portalError">{error}</div>}<section className="v13GatewayHero"><div><span>PROVIDER-NEUTRAL WORKSPACE GATEWAY</span><h2>Claude, Gemini, OpenClaw or future agents use the same workspace protocol.</h2><p>The provider session never receives repository credentials. It gets bounded read/write/snapshot capabilities, then hands source to Artifact Registry for Commit Agent processing.</p><div className="v13Protocol"><b>Provider Agent</b><i>→</i><b>Gateway Session</b><i>→</i><b>Dev Workspace</b><i>→</i><b>Artifact Snapshot</b><i>→</i><b>Commit Agent</b></div></div><aside><code>read</code><code>write</code><code>snapshot</code><code>close</code></aside></section>
 <div className="v13Split"><section className="v8Card"><div className="v8CardHead"><div><b>Active gateway sessions</b><small>Identity + provider + workspace lease</small></div></div><div className="v13SessionTable"><div className="head"><span>ID</span><span>Provider</span><span>Workspace</span><span>Member</span><span>Status</span></div>{sessions.map(x=><div key={x.id}><b>#{x.id}</b><span>{x.provider}</span><span>#{x.workspace_id}</span><span>#{x.member_id||"—"}</span><em>{x.status}</em></div>)}{!sessions.length&&<div className="v8Empty">No gateway sessions yet</div>}</div></section>
 <section className="v8Card"><div className="v8CardHead"><div><b>Execution fabric</b><small>Isolation provider contract</small></div></div><div className="v13Providers">{providers.map(x=><article key={x.provider}><div><b>{x.provider}</b><em>{x.isolation}</em></div><small>{x.notes}</small><footer><span>{x.network_policy?"Network policy":"No network policy"}</span><span>{x.secrets_mount?"Secret mounts":"No secret mounts"}</span></footer></article>)}</div></section></div>
 <section className="v8Card"><div className="v8CardHead"><div><b>Workspace operations audit</b><small>Every provider write/read/snapshot becomes a durable operation record.</small></div></div><div className="v13Ops"><div className="head"><span>Session</span><span>Operation</span><span>Path</span><span>Artifact</span><span>Status</span></div>{ops.slice(0,12).map(x=><div key={x.id}><span>#{x.session_id}</span><b>{x.operation_type}</b><code>{x.logical_path||"—"}</code><span>{x.artifact_id?`#${x.artifact_id}`:"—"}</span><em>{x.status}</em></div>)}</div></section></>
}
