"use client";
import {useEffect,useState} from "react";
import {AuthGate} from "./AuthGate";
import {V8AppShell} from "./V8AppShell";
import {api,apiV8} from "../lib/api";
import {activeOrganizationId} from "../lib/auth";

type WF={id:number;name:string;trigger_type:string;status:string};
const starter={nodes:[{id:"trigger",type:"trigger",label:"Task created"},{id:"research",type:"agent",label:"Research agent"},{id:"draft",type:"agent",label:"Create draft"},{id:"approval",type:"approval",label:"Manager approval"},{id:"publish",type:"tool",label:"Publish output"}],edges:[{source:"trigger",target:"research"},{source:"research",target:"draft"},{source:"draft",target:"approval"},{source:"approval",target:"publish"}]};
export function WorkflowBuilderConsole(){const org=activeOrganizationId();const [flows,setFlows]=useState<WF[]>([]),[selected,setSelected]=useState<number|undefined>(),[graph,setGraph]=useState<any>(starter),[versions,setVersions]=useState<any[]>([]),[error,setError]=useState(""),[saved,setSaved]=useState("");async function load(){try{const f=await api.workflows(org) as WF[];setFlows(f);if(f.length&&!selected)setSelected(f[0].id)}catch(e:any){setError(e.message)}}useEffect(()=>{load()},[]);useEffect(()=>{if(selected)apiV8.workflowGraphVersions(selected).then((v:any)=>{setVersions(v);if(v[0])try{setGraph(JSON.parse(v[0].graph_json))}catch{}}).catch(()=>{})},[selected]);async function save(publish:boolean){if(!selected)return;setError("");try{const v:any=await apiV8.saveWorkflowGraph(selected,graph,publish);setSaved(`Saved v${v.version}${publish?" · published":""}`);setVersions(await apiV8.workflowGraphVersions(selected) as any[])}catch(e:any){setError(e.message)}}function addNode(){const id=`step-${Date.now()}`;setGraph({...graph,nodes:[...graph.nodes,{id,type:"agent",label:"New agent step"}]})}
 return <AuthGate><V8AppShell title="Workflow Builder" subtitle="Versioned DAG model for visual company automation" action={<><button className="v8Ghost" onClick={()=>save(false)}>Save draft</button><button className="v8Primary" onClick={()=>save(true)}>Publish</button></>}><div className="v8Builder"><aside className="v8Card v8FlowList"><div className="v8CardHead"><div><b>Workflows</b><span>{flows.length} definitions</span></div></div>{flows.map(f=><button key={f.id} className={selected===f.id?"active":""} onClick={()=>setSelected(f.id)}><b>{f.name}</b><span>{f.trigger_type} · {f.status}</span></button>)}</aside><section className="v8Card v8Canvas"><div className="v8CardHead"><div><b>Visual graph</b><span>Nodes + edges are validated as an acyclic graph</span></div><button className="v8Ghost" onClick={addNode}>+ Node</button></div>{error&&<div className="v8Error">{error}</div>}{saved&&<div className="v8Success">{saved}</div>}<div className="v8Graph">{graph.nodes.map((n:any,i:number)=><div key={n.id} className={`v8Node ${n.type}`}><small>{n.type.toUpperCase()}</small><input value={n.label} onChange={e=>{const nodes=[...graph.nodes];nodes[i]={...n,label:e.target.value};setGraph({...graph,nodes})}}/><code>{n.id}</code>{i<graph.nodes.length-1&&<i className="v8Arrow">→</i>}</div>)}</div><div className="v8EdgeEditor"><b>Edges</b>{graph.edges.map((e:any,i:number)=><div key={i}><code>{e.source}</code><span>→</span><code>{e.target}</code></div>)}</div></section><aside className="v8Card v8Versions"><div className="v8CardHead"><div><b>Versions</b><span>Immutable graph snapshots</span></div></div>{versions.map(v=><div className="v8Version" key={v.id}><b>v{v.version}</b><span>{v.published?"Published":"Draft"}</span></div>)}</aside></div></V8AppShell></AuthGate>}
